AWSTemplateFormatVersion: '2010-09-09'
Description: API Gateway + Lambda (Python) para catálogo, carrito y pagos con Mercado Pago.

Parameters:
  StageName:
    Type: String
    Default: prod
    Description: Nombre del stage de API Gateway.
  CognitoUserPoolArn:
    Type: String
    Description: ARN del User Pool para el authorizer JWT.
  LambdaCodeS3Bucket:
    Type: String
    Description: Bucket con los artefactos ZIP de Lambda.
  LambdaCodeS3Key:
    Type: String
    Description: Ruta del ZIP con el código de las funciones (usado por defecto).

Resources:
  ProductsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: tenantId
          AttributeType: S
        - AttributeName: productId
          AttributeType: S
        - AttributeName: category
          AttributeType: S
        - AttributeName: status
          AttributeType: S
        - AttributeName: slug
          AttributeType: S
      KeySchema:
        - AttributeName: tenantId
          KeyType: HASH
        - AttributeName: productId
          KeyType: RANGE
      TableName: !Sub '${AWS::StackName}-products'
      GlobalSecondaryIndexes:
        - IndexName: CategoryIndex
          KeySchema:
            - AttributeName: tenantId
              KeyType: HASH
            - AttributeName: category
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: SlugIndex
          KeySchema:
            - AttributeName: tenantId
              KeyType: HASH
            - AttributeName: slug
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  OrdersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: tenantId
          AttributeType: S
        - AttributeName: orderId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: status
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
        - AttributeName: updatedAt
          AttributeType: S
      KeySchema:
        - AttributeName: tenantId
          KeyType: HASH
        - AttributeName: orderId
          KeyType: RANGE
      TableName: !Sub '${AWS::StackName}-orders'
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      GlobalSecondaryIndexes:
        - IndexName: OrdersByUser
          KeySchema:
            - AttributeName: tenantId
              KeyType: HASH
            - AttributeName: userId
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: OrdersByStatus
          KeySchema:
            - AttributeName: tenantId
              KeyType: HASH
            - AttributeName: status
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  CartsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: tenantId
          AttributeType: S
        - AttributeName: cartId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
      KeySchema:
        - AttributeName: tenantId
          KeyType: HASH
        - AttributeName: cartId
          KeyType: RANGE
      TableName: !Sub '${AWS::StackName}-carts'
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      GlobalSecondaryIndexes:
        - IndexName: UserCartIndex
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  TransactionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: tenantId
          AttributeType: S
        - AttributeName: transactionId
          AttributeType: S
        - AttributeName: orderId
          AttributeType: S
        - AttributeName: status
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
      KeySchema:
        - AttributeName: tenantId
          KeyType: HASH
        - AttributeName: transactionId
          KeyType: RANGE
      TableName: !Sub '${AWS::StackName}-transactions'
      GlobalSecondaryIndexes:
        - IndexName: TransactionsByOrder
          KeySchema:
            - AttributeName: tenantId
              KeyType: HASH
            - AttributeName: orderId
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: TransactionsByStatus
          KeySchema:
            - AttributeName: tenantId
              KeyType: HASH
            - AttributeName: status
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: BusinessAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource:
                  - !GetAtt ProductsTable.Arn
                  - !GetAtt OrdersTable.Arn
                  - !GetAtt CartsTable.Arn
                  - !GetAtt TransactionsTable.Arn
                  - !Sub '${OrdersTable.Arn}/stream/*'
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                  - kms:Decrypt
                Resource: '*'

  ApiFunction:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.11
      Handler: app.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref LambdaCodeS3Bucket
        S3Key: !Ref LambdaCodeS3Key
      Environment:
        Variables:
          PRODUCTS_TABLE: !Ref ProductsTable
          ORDERS_TABLE: !Ref OrdersTable
          CARTS_TABLE: !Ref CartsTable
          TRANSACTIONS_TABLE: !Ref TransactionsTable
      Timeout: 30

  ApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub '${AWS::StackName}-api'
      EndpointConfiguration:
        Types: [REGIONAL]

  ApiAuthorizer:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      Name: CognitoJWT
      Type: COGNITO_USER_POOLS
      IdentitySource: method.request.header.Authorization
      ProviderARNs:
        - !Ref CognitoUserPoolArn
      RestApiId: !Ref ApiGateway

  ApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt ApiGateway.RootResourceId
      PathPart: v1
      RestApiId: !Ref ApiGateway

  ProductsResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref ApiResource
      PathPart: products
      RestApiId: !Ref ApiGateway

  ProductByIdResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref ProductsResource
      PathPart: '{id}'
      RestApiId: !Ref ApiGateway

  CartResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref ApiResource
      PathPart: cart
      RestApiId: !Ref ApiGateway

  OrdersResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref ApiResource
      PathPart: orders
      RestApiId: !Ref ApiGateway

  WebhooksResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref ApiResource
      PathPart: webhooks
      RestApiId: !Ref ApiGateway

  MercadoPagoWebhookResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref WebhooksResource
      PathPart: mercadopago
      RestApiId: !Ref ApiGateway

  AnalyticsResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref ApiResource
      PathPart: analytics
      RestApiId: !Ref ApiGateway

  SalesAnalyticsResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref AnalyticsResource
      PathPart: sales
      RestApiId: !Ref ApiGateway

  ProductsGetMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: COGNITO_USER_POOLS
      AuthorizerId: !Ref ApiAuthorizer
      HttpMethod: GET
      ResourceId: !Ref ProductsResource
      RestApiId: !Ref ApiGateway
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ApiFunction.Arn}/invocations'
      MethodResponses:
        - StatusCode: 200

  ProductByIdGetMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: COGNITO_USER_POOLS
      AuthorizerId: !Ref ApiAuthorizer
      HttpMethod: GET
      ResourceId: !Ref ProductByIdResource
      RestApiId: !Ref ApiGateway
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ApiFunction.Arn}/invocations'
      MethodResponses:
        - StatusCode: 200

  CartGetMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: COGNITO_USER_POOLS
      AuthorizerId: !Ref ApiAuthorizer
      HttpMethod: GET
      ResourceId: !Ref CartResource
      RestApiId: !Ref ApiGateway
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ApiFunction.Arn}/invocations'
      MethodResponses:
        - StatusCode: 200

  CartPostMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: COGNITO_USER_POOLS
      AuthorizerId: !Ref ApiAuthorizer
      HttpMethod: POST
      ResourceId: !Ref CartResource
      RestApiId: !Ref ApiGateway
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ApiFunction.Arn}/invocations'
      MethodResponses:
        - StatusCode: 200

  OrdersPostMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: COGNITO_USER_POOLS
      AuthorizerId: !Ref ApiAuthorizer
      HttpMethod: POST
      ResourceId: !Ref OrdersResource
      RestApiId: !Ref ApiGateway
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ApiFunction.Arn}/invocations'
      MethodResponses:
        - StatusCode: 200

  WebhookMercadoPagoPostMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: POST
      ResourceId: !Ref MercadoPagoWebhookResource
      RestApiId: !Ref ApiGateway
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ApiFunction.Arn}/invocations'
      MethodResponses:
        - StatusCode: 200

  AnalyticsGetMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: COGNITO_USER_POOLS
      AuthorizerId: !Ref ApiAuthorizer
      HttpMethod: GET
      ResourceId: !Ref SalesAnalyticsResource
      RestApiId: !Ref ApiGateway
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ApiFunction.Arn}/invocations'
      MethodResponses:
        - StatusCode: 200

  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - ProductsGetMethod
      - ProductByIdGetMethod
      - CartGetMethod
      - CartPostMethod
      - OrdersPostMethod
      - WebhookMercadoPagoPostMethod
      - AnalyticsGetMethod
    Properties:
      RestApiId: !Ref ApiGateway
      StageName: !Ref StageName
      Description: Despliegue de la API principal.

  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ApiFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGateway}/*/*/*'

Outputs:
  ApiUrl:
    Description: URL base del API Gateway.
    Value: !Sub 'https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${StageName}'
  ProductsTableName:
    Description: Nombre de la tabla DynamoDB de productos.
    Value: !Ref ProductsTable
  OrdersTableName:
    Description: Nombre de la tabla DynamoDB de órdenes.
    Value: !Ref OrdersTable
  CartsTableName:
    Description: Nombre de la tabla DynamoDB de carritos.
    Value: !Ref CartsTable
  TransactionsTableName:
    Description: Nombre de la tabla DynamoDB de transacciones de pago.
    Value: !Ref TransactionsTable
