AWSTemplateFormatVersion: '2010-09-09'
Description: Cognito User Pool y App Client para frontend/back office con JWT.

Parameters:
  TenantId:
    Type: String
    Description: Identificador único del tenant para construir los nombres de recursos.
  UserPoolName:
    Type: String
    Default: ''
    Description: Nombre del User Pool. Si se deja vacío se usará un nombre derivado del tenant.
  CallbackUrls:
    Type: CommaDelimitedList
    Description: URLs de callback (frontend y back office).
  LogoutUrls:
    Type: CommaDelimitedList
    Description: URLs de logout.
  CognitoDomainPrefix:
    Type: String
    Default: ''
    Description: Prefijo opcional para el dominio hospedado de Cognito. Si no se define se genera con el tenant.

Conditions:
  UseCustomPoolName: !Not [!Equals [!Ref UserPoolName, '']]
  UseCustomDomainPrefix: !Not [!Equals [!Ref CognitoDomainPrefix, '']]

Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !If [UseCustomPoolName, !Ref UserPoolName, !Sub 'pocweb-${TenantId}-users']
      AutoVerifiedAttributes: [email]
      UsernameAttributes: [email]
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
          RequireUppercase: true
      Schema:
        - Name: email
          Required: true
          Mutable: true
          AttributeDataType: String
        - Name: tenantId
          Required: true
          Mutable: true
          AttributeDataType: String

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub 'web-${TenantId}'
      UserPoolId: !Ref UserPool
      AllowedOAuthFlows: [code]
      AllowedOAuthScopes: [openid, email, profile]
      AllowedOAuthFlowsUserPoolClient: true
      CallbackURLs: !Ref CallbackUrls
      LogoutURLs: !Ref LogoutUrls
      SupportedIdentityProviders: [COGNITO]
      GenerateSecret: false
      ReadAttributes:
        - email
        - custom:tenantId
      WriteAttributes:
        - email
        - custom:tenantId

  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !If
        - UseCustomDomainPrefix
        - !Ref CognitoDomainPrefix
        - !Sub '${TenantId}-${AWS::AccountId}'
      UserPoolId: !Ref UserPool

  AdminGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: admin
      UserPoolId: !Ref UserPool
      Description: Administradores del back office.

  CustomerGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: customer
      UserPoolId: !Ref UserPool
      Description: Clientes finales.

Outputs:
  UserPoolId:
    Description: ID del User Pool para JWT.
    Value: !Ref UserPool
  UserPoolClientId:
    Description: ID del App Client para el frontend/back office.
    Value: !Ref UserPoolClient
  UserPoolArn:
    Description: ARN del User Pool para usar en el authorizer de API Gateway.
    Value: !GetAtt UserPool.Arn
  UserPoolRegion:
    Description: Región donde se creó el User Pool.
    Value: !Ref AWS::Region
  HostedDomain:
    Description: Dominio asignado al Hosted UI de Cognito.
    Value: !If [UseCustomDomainPrefix, !Ref CognitoDomainPrefix, !Sub '${TenantId}-${AWS::AccountId}']
  HostedUiIssuer:
    Description: Issuer URL que consumen las apps para validar JWT.
    Value: !Sub 'https://cognito-idp.${AWS::Region}.amazonaws.com/${UserPool}'
